Category.create(name:'kz')
Category.create(name:'中村　匠')
Category.create(name:'渡辺　翔')
Category.create(name:'吉田　ゐさお')
Category.create(name:'角野　寿和')
Category.create(name:'Carlos K')
Category.create(name:'町田　紀彦,吉松　隆')
Category.create(name:'小田桐　ゆうき')
Category.create(name:'オオヤギヒロオ')
Category.create(name:'ryo')
Category.create(name:'丸山　真由子')
Category.create(name:'渡辺　和紀')
Category.create(name:'重永　亮介')
Category.create(name:'TSUKASA')
Category.create(name:'佐久間　誠')
Category.create(name:'飯田　清澄')
Category.create(name:'nori')
Category.create(name:'KOH')
Category.create(name:'伊田　学')
Category.create(name:'小野　貴光')
Category.create(name:'栗原　稔,岩田　アッチュ')
Category.create(name:'日向　大介')
Category.create(name:'呉田　軽穂')
Category.create(name:'武田　城似,PENGUINS PROJECT')
Category.create(name:'Watana Besta SOCIAL Club')
Category.create(name:'長沢　智亜紀,永野　小織')
Category.create(name:'野村　陽一郎')
Category.create(name:'湯浅　篤')
Category.create(name:'小川　智之')
Category.create(name:'じん')
Category.create(name:'megane')
Category.create(name:'中尾　昌史')
Category.create(name:'武田　城似,櫻井　亮')
Category.create(name:'町田　紀彦')
Category.create(name:'奥井　香')
Category.create(name:'宮川　泰')
Category.create(name:'毛蟹')
Category.create(name:'宮永　治郎')
Category.create(name:'秋葉　広大')
Music.create(name:'君の夢を見よう', lyricist:'kz', year:'2010',position:'シングル',category_id:'1')
Music.create(name:'DROP', lyricist:'kz', year:'2010',position:'シングル' ,category_id:'1')
Music.create(name:'irony', lyricist:'kz', year:'2010',position:'シングル' ,category_id:'1')
Music.create(name:'ココロの引力', lyricist:'mavie', year:'2010',position:'カップリング' ,category_id:'2')
Music.create(name:'Neo Moon', lyricist:'奥村　イオン', year:'2010',position:'カップリング' ,category_id:'4')
Music.create(name:'コネクト', lyricist:'渡辺　翔', year:'2011',position:'シングル' ,category_id:'3')
Music.create(name:'Dreamin', lyricist:'角野　寿和', year:'2011',position:'カップリング' ,category_id:'5')
Music.create(name:'キミとふたり', lyricist:'Carlos K', year:'2011',position:'カップリング' ,category_id:'6')
Music.create(name:'true blue', lyricist:'町田　紀彦', year:'2011',position:'カバー' ,category_id:'7')
Music.create(name:'nexus', lyricist:'kz', year:'2011',position:'シングル' ,category_id:'1')
Music.create(name:'Dont cry', lyricist:'小田桐　ゆうき', year:'2011',position:'カップリング' ,category_id:'8')
Music.create(name:'アナタニFIT', lyricist:'オオヤギヒロオ', year:'2012',position:'カップリング' ,category_id:'9')
Music.create(name:'ナイショの話', lyricist:'ryo', year:'2012',position:'シングル' ,category_id:'10')
Music.create(name:'Im in Love', lyricist:'丸山　真由子', year:'2012',position:'カップリング' ,category_id:'11')
Music.create(name:'本当は', lyricist:'Carlos K', year:'2012',position:'カップリング' ,category_id:'6')
Music.create(name:'サヨナラは言わない', lyricist:'角野　寿和', year:'2012',position:'アルバム' ,category_id:'5')
Music.create(name:'恋磁石', lyricist:'渡辺　和紀', year:'2012',position:'アルバム' ,category_id:'12')
Music.create(name:'メモリー', lyricist:'丸山　真由子', year:'2012',position:'アルバム' ,category_id:'11')
Music.create(name:'flowery', lyricist:'kz', year:'2012',position:'アルバム' ,category_id:'1')
Music.create(name:'プロミス', lyricist:'渡辺　翔', year:'2012',position:'アルバム' ,category_id:'3')
Music.create(name:'graduation', lyricist:'丸山　真由子', year:'2012',position:'アルバム' ,category_id:'11')
Music.create(name:'treasure', lyricist:'重永　亮介', year:'2012',position:'アルバム' ,category_id:'13')
Music.create(name:'zutto', lyricist:'丸山　真由子', year:'2012',position:'アルバム' ,category_id:'11')
Music.create(name:'NEN・DO・ROIDO', lyricist:'TSUKASA', year:'2012',position:'アルバム' ,category_id:'14')
Music.create(name:'Wake Up', lyricist:'丸山　真由子', year:'2012',position:'シングル' ,category_id:'14')
Music.create(name:'泣かないよ', lyricist:'重永　亮介', year:'2012',position:'カップリング' ,category_id:'13')
Music.create(name:'a moment', lyricist:'奥村　イオン', year:'2012',position:'カップリング' ,category_id:'14')
Music.create(name:'ルミナス', lyricist:'渡辺　翔', year:'2012',position:'シングル' ,category_id:'3')
Music.create(name:'friends', lyricist:'角野　寿和', year:'2012',position:'カップリング' ,category_id:'5')
Music.create(name:'blossom', lyricist:'重永　亮介', year:'2012',position:'カップリング' ,category_id:'13')
Music.create(name:'reunion', lyricist:'kz', year:'2013',position:'シングル' ,category_id:'1')
Music.create(name:'Tik Tak', lyricist:'飯田　清澄', year:'2013',position:'カップリング' ,category_id:'16')
Music.create(name:'ミントガム', lyricist:'奥村　イオン', year:'2013',position:'カップリング' ,category_id:'15')
Music.create(name:'SECOND STORY', lyricist:'ClariS', year:'2013',position:'アルバム' ,category_id:'17')
Music.create(name:'ハルラ', lyricist:'角野　寿和', year:'2013',position:'アルバム' ,category_id:'5')
Music.create(name:'rainy day', lyricist:'KOH', year:'2013',position:'アルバム' ,category_id:'18')
Music.create(name:'HANABI', lyricist:'丸山　真由子', year:'2013',position:'アルバム' ,category_id:'11')
Music.create(name:'with you', lyricist:'丸山　真由子', year:'2013',position:'アルバム' ,category_id:'11')
Music.create(name:'ダイアリー', lyricist:'KOH', year:'2013',position:'アルバム' ,category_id:'18')
Music.create(name:'etarnally', lyricist:'丸山　真由子', year:'2013',position:'アルバム' ,category_id:'11')
Music.create(name:'ひとつだけ', lyricist:'重永　亮介', year:'2013',position:'アルバム' ,category_id:'13')
Music.create(name:'グラスプ', lyricist:'渡辺　翔', year:'2013',position:'アルバム' ,category_id:'3')
Music.create(name:'カラフル', lyricist:'渡辺　翔', year:'2013',position:'シングル' ,category_id:'3')
Music.create(name:'Surely', lyricist:'伊田　学', year:'2013',position:'カップリング' ,category_id:'19')
Music.create(name:'Pieces', lyricist:'丸山　真由子', year:'2013',position:'カップリング' ,category_id:'11')
Music.create(name:'CLICK', lyricist:'kz', year:'2014',position:'シングル' ,category_id:'1')
Music.create(name:'シルシ', lyricist:'角野　寿和', year:'2014',position:'カップリング' ,category_id:'5')
Music.create(name:'next to you', lyricist:'伊田　学', year:'2014',position:'カップリング' ,category_id:'19')
Music.create(name:'STEP', lyricist:'kz', year:'2014',position:'シングル' ,category_id:'1')
Music.create(name:'ドリームワールド', lyricist:'KOH', year:'2014',position:'カップリング' ,category_id:'18')
Music.create(name:'桜咲く', lyricist:'伊田　学', year:'2014',position:'カップリング' ,category_id:'19')
Music.create(name:'Drawing', lyricist:'角野　寿和', year:'2014',position:'アルバム' ,category_id:'5')
Music.create(name:'眠り姫', lyricist:'重永　亮介', year:'2014',position:'アルバム' ,category_id:'13')
Music.create(name:'Time', lyricist:'KOH', year:'2014',position:'アルバム' ,category_id:'18')
Music.create(name:'RESTART', lyricist:'丸山　真由子', year:'2014',position:'アルバム' ,category_id:'11')
Music.create(name:'コイノミ', lyricist:'磯谷　佳江', year:'2014',position:'アルバム' ,category_id:'20')
Music.create(name:'ドライフラワー', lyricist:'奥村　イオン', year:'2014',position:'アルバム' ,category_id:'15')
Music.create(name:'トパーズ', lyricist:'渡辺　翔', year:'2014',position:'アルバム' ,category_id:'3')
Music.create(name:'かくれんぼ', lyricist:'伊田　学', year:'2014',position:'アルバム' ,category_id:'19')
Music.create(name:'orenge', lyricist:'丸山　真由子', year:'2014',position:'アルバム' ,category_id:'11')
Music.create(name:'Clear Sky', lyricist:'丸山　真由子', year:'2014',position:'シングル' ,category_id:'11')
Music.create(name:'border', lyricist:'meg rock', year:'2015',position:'シングル' ,category_id:'13')
Music.create(name:'Reflect', lyricist:'KOH', year:'2015',position:'カップリング' ,category_id:'18')
Music.create(name:'カイト', lyricist:'渡辺　翔', year:'2015',position:'カップリング' ,category_id:'3')
Music.create(name:'アネモネ', lyricist:'KOH', year:'2015',position:'シングル' ,category_id:'18')
Music.create(name:'YUMENOKI', lyricist:'磯谷　佳江', year:'2015',position:'カップリング' ,category_id:'20')
Music.create(name:'pastel', lyricist:'KOH', year:'2015',position:'カップリング' ,category_id:'18')
Music.create(name:'Prism', lyricist:'重永　亮介', year:'2015',position:'シングル' ,category_id:'13')
Music.create(name:'SECRET', lyricist:'丸山　真由子', year:'2015',position:'カップリング' ,category_id:'11')
Music.create(name:'セピア', lyricist:'KOH', year:'2015',position:'カップリング' ,category_id:'18')
Music.create(name:'ひらひら　ひらら', lyricist:'奥村　イオン', year:'2016',position:'シングル' ,category_id:'15')
Music.create(name:'さよならメモリーズ', lyricist:'ryo', year:'2016',position:'カバー' ,category_id:'10')
Music.create(name:'sakura', lyricist:'岩田　アッチュ', year:'2016',position:'カバー' ,category_id:'21')
Music.create(name:'明日、春が来たら', lyricist:'坂元　裕二', year:'2016',position:'カバー' ,category_id:'22')
Music.create(name:'赤いスイートピー', lyricist:'松本　隆', year:'2016',position:'カバー' ,category_id:'23')
Music.create(name:'Gravity', lyricist:'武田　城似,PENGUINS PROJECT', year:'2016',position:'シングル' ,category_id:'24')
Music.create(name:'Cloudy', lyricist:'KOH', year:'2016',position:'カップリング' ,category_id:'18')
Music.create(name:'アワイ　オモイ', lyricist:'Watana Besta SOCIAL Club', year:'2016',position:'シングル' ,category_id:'18')
Music.create(name:'clever', lyricist:'KOH', year:'2016',position:'シングル' ,category_id:'18')
Music.create(name:'again', lyricist:'丸山　真由子', year:'2016',position:'シングル' ,category_id:'11')
Music.create(name:'Collage', lyricist:'磯谷　佳江', year:'2016',position:'カップリング' ,category_id:'20')
Music.create(name:'コネクト -2017-', lyricist:'渡辺　翔', year:'2016',position:'リレコーディング' ,category_id:'3')
Music.create(name:'ホログラム', lyricist:'重永　亮介', year:'2017',position:'アルバム' ,category_id:'13')
Music.create(name:'水色クラゲ', lyricist:'渡辺　翔', year:'2017',position:'アルバム' ,category_id:'3')
Music.create(name:'このiは虚数', lyricist:'長沢　智亜紀,永野　小織', year:'2017',position:'アルバム' ,category_id:'26')
Music.create(name:'ウソツキ', lyricist:'丸山　真由子', year:'2017',position:'アルバム' ,category_id:'11')
Music.create(name:'recall', lyricist:'KOH', year:'2017',position:'アルバム' ,category_id:'18')
Music.create(name:'ルミナス -2017-', lyricist:'渡辺　翔', year:'2017',position:'リレコーディング' ,category_id:'3')
Music.create(name:'カラフル', lyricist:'渡辺　翔', year:'2017',position:'リレコーディング' ,category_id:'3')
Music.create(name:'ヒトリゴト', lyricist:'ケリー', year:'2017',position:'シングル' ,category_id:'27')
Music.create(name:'イロドリ', lyricist:'KAREN', year:'2017',position:'カップリング' ,category_id:'28')
Music.create(name:'Butterfly Regret', lyricist:'長沢　智亜紀,永野　小織', year:'2017',position:'カップリング' ,category_id:'26')
Music.create(name:'SHOIRI', lyricist:'小川　智之', year:'2017',position:'シングル' ,category_id:'29')
Music.create(name:'君の知らない物語', lyricist:'ryo', year:'2017',position:'カバー' ,category_id:'10')
Music.create(name:'アイヲウタエ', lyricist:'じん', year:'2017',position:'カバー' ,category_id:'30')
Music.create(name:'ナイショの話 -2017-', lyricist:'ryo', year:'2012',position:'リレコーディング' ,category_id:'10')
Music.create(name:'border -remix-', lyricist:'meg rock', year:'2015',position:'リレコーディング' ,category_id:'13')
Music.create(name:'PRIMALove', lyricist:'kz', year:'2018',position:'シングル' ,category_id:'1')
Music.create(name:'冬空花火', lyricist:'kz', year:'2018',position:'カップリング' ,category_id:'1')
Music.create(name:'irony -season 02-', lyricist:'kz', year:'2018',position:'リレコーディング' ,category_id:'1')
Music.create(name:'CheerS', lyricist:'ハヤシケイ', year:'2018',position:'シングル' ,category_id:'31')
Music.create(name:'ねがい', lyricist:'丸山　真由子', year:'2018',position:'カップリング' ,category_id:'11')
Music.create(name:'Wake Up -season 02-', lyricist:'丸山　真由子', year:'2018',position:'カップリング' ,category_id:'11')
Music.create(name:'Overtune', lyricist:'なし', year:'2018',position:'アルバム' ,category_id:'32')
Music.create(name:'1/f', lyricist:'長沢　智亜紀,永野　小織', year:'2018',position:'アルバム' ,category_id:'26')
Music.create(name:'陽だまり', lyricist:'KAREN', year:'2018',position:'アルバム' ,category_id:'33')
Music.create(name:'distance', lyricist:'KOH', year:'2018',position:'アルバム' ,category_id:'18')
Music.create(name:'パラレルワープ', lyricist:'長沢　智亜紀,永野　小織', year:'2018',position:'アルバム' ,category_id:'26')
Music.create(name:'Last Squall', lyricist:'長沢　智亜紀,永野　小織', year:'2018',position:'アルバム' ,category_id:'26')
Music.create(name:'TRAVEL', lyricist:'磯谷　佳江', year:'2018',position:'アルバム' ,category_id:'20')
Music.create(name:'Time Tunnel', lyricist:'なし', year:'2018',position:'アルバム' ,category_id:'32')
Music.create(name:'シニカルサスペンス', lyricist:'重永　亮介', year:'2018',position:'アルバム' ,category_id:'13')
Music.create(name:'Fairy Party', lyricist:'長沢　智亜紀,永野　小織', year:'2018',position:'アルバム' ,category_id:'26')
Music.create(name:'secret base 〜君がくれたもの〜', lyricist:'町田　紀彦', year:'2019',position:'カバー' ,category_id:'34')
Music.create(name:'Diamonds', lyricist:'中山　加奈子', year:'2019',position:'カバー' ,category_id:'35')
Music.create(name:'タッチ', lyricist:'庵　珍化', year:'2019',position:'カバー' ,category_id:'36')
Music.create(name:'Summer Delay', lyricist:'長沢　智亜紀,永野　小織', year:'2019',position:'シングル' ,category_id:'26')
Music.create(name:'アリシア', lyricist:'毛蟹', year:'2020',position:'シングル' ,category_id:'37')
Music.create(name:'シグナル', lyricist:'磯谷　佳江', year:'2020',position:'アルバム' ,category_id:'28')
Music.create(name:'ユニゾン', lyricist:'ClariS', year:'2020',position:'アルバム' ,category_id:'38')
Music.create(name:'STEP -season 02-', lyricist:'kz', year:'2020',position:'リレコーディング' ,category_id:'1')
Music.create(name:'CLICK -season 02-', lyricist:'kz', year:'2020',position:'リレコーディング' ,category_id:'1')
Music.create(name:'nexus -season 02-', lyricist:'kz', year:'2020',position:'リレコーディング' ,category_id:'1')
Music.create(name:'ひらひら　ひらら -Clala solo ver.-', lyricist:'奥村　イオン', year:'2020',position:'リレコーディング' ,category_id:'15')
Music.create(name:'recall -Karen solo ver.-', lyricist:'KOH', year:'2020',position:'リレコーディング' ,category_id:'18')
Music.create(name:'仮面ジュブナイル', lyricist:'重永　亮介', year:'2020',position:'リレコーディング' ,category_id:'13')
Music.create(name:'Dreamin -Karen solo ver.-', lyricist:'角野　寿和', year:'2020',position:'リレコーディング' ,category_id:'5')
Music.create(name:'泣かないよ -Clala solo ver.-', lyricist:'重永　亮介', year:'2020',position:'リレコーディング' ,category_id:'13')
Music.create(name:'PRECIOUS', lyricist:'丸山　真由子', year:'2020',position:'シングル' ,category_id:'11')
Music.create(name:'Fight!!', lyricist:'KOH', year:'2021',position:'シングル' ,category_id:'18')
Music.create(name:'Brave', lyricist:'ClariS', year:'2021',position:'カップリング' ,category_id:'39')
Music.create(name:'恋待かぐや', lyricist:'重永　亮介', year:'2021',position:'カップリング' ,category_id:'13')